### ISSUE TITLE
Planum login window layout

### ISSUE THREAD

**Issue by cryptojoystick** [scryptachain/scrypta-planum-website#1]
Uniform layout of https://planum.dev/#/login with the same graphic layout of https://electio.app/#/

![image](https://user-images.githubusercontent.com/56955507/79471819-5d7dbc80-8003-11ea-8fa3-241a4adb0108.png)

![image](https://user-images.githubusercontent.com/56955507/79471900-78e8c780-8003-11ea-9b8d-391fd5abc5ae.png)
Add link to ScryptaID extension

**Comment by turinglabsorg** [comment]
Solved in `development` branch
